import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import assert from 'node:assert/strict'

const source = readFileSync(join(import.meta.dirname, 'src/main.ts'), 'utf8')
const html = readFileSync(join(import.meta.dirname, 'index.html'), 'utf8')
const style = readFileSync(join(import.meta.dirname, 'src/style.css'), 'utf8')

assert.match(source, /rfb\.viewOnly\s*=\s*false/, 'browser live viewer must allow mouse and keyboard input')
assert.doesNotMatch(source, /rfb\.viewOnly\s*=\s*true/, 'browser live viewer must not be read-only')
assert.match(source, /window\.close\(\)/, 'browser live viewer must close itself after a clean handoff disconnect')
assert.match(source, /new EventSource\(/, 'browser live viewer must subscribe to virtual pointer events')
assert.match(source, /lastPointerSnapshot/, 'browser live viewer must keep the latest pointer snapshot until noVNC canvas is ready')
assert.match(source, /requestAnimationFrame/, 'browser live viewer must retry initial pointer rendering after canvas mount')
assert.match(source, /contentOffsetY:\s*number/, 'browser live viewer must accept browser content vertical offset')
assert.match(source, /contentOffsetY\s*\+\s*snapshot\.viewportHeight/, 'browser live viewer must map page y through the browser content area')
assert.match(source, /contentOffsetY\s*\+\s*snapshot\.y/, 'browser live viewer must add browser chrome height to virtual pointer y')
assert.doesNotMatch(source, /dataset\.visible\s*=\s*['"]false['"]/, 'virtual pointer must never be hidden while the viewer is open')
assert.doesNotMatch(source, /setStatus\(['"]Connected['"]\)/, 'browser live viewer must not show a connected status label')
assert.match(source, /setScreenBusy\(true\)/, 'browser live viewer must mark the screen busy while connecting')
assert.match(source, /setScreenBusy\(false\)/, 'browser live viewer must clear the busy state after connecting')
assert.match(html, /id="status"[^>]+aria-label="Connecting"[^>]*><\/div>/, 'loading indicator must have an accessible name without visible text')
assert.match(html, /id="virtual-pointer"/, 'browser live viewer must include a virtual pointer overlay element')
assert.match(html, /virtual-pointer__icon/, 'browser live viewer must render a cursor-shaped SVG pointer')
assert.match(html, /viewBox="0 0 24 24"/, 'virtual pointer SVG must preserve the source cursor geometry')
assert.match(html, /virtual-pointer__press/, 'browser live viewer must include a click feedback element')
assert.doesNotMatch(html, /virtual-pointer__halo/, 'virtual pointer must not use a permanent halo that obscures the click target')
assert.match(style, /animation:\s*viewer-spin/, 'browser live viewer loading indicator must animate as a spinner')
assert.match(style, /@keyframes\s+viewer-spin/, 'browser live viewer spinner must define a rotation animation')
assert.match(style, /#virtual-pointer/, 'browser live viewer must style the virtual pointer overlay')
assert.match(style, /pointer-events:\s*none/, 'virtual pointer overlay must not intercept user input')
assert.match(style, /--pointer-hotspot-x:\s*4px/, 'virtual pointer coordinate must align to the cursor tip x hotspot')
assert.match(style, /--pointer-hotspot-y:\s*4px/, 'virtual pointer coordinate must align to the cursor tip y hotspot')
assert.match(style, /calc\(var\(--pointer-x\) - var\(--pointer-hotspot-x\)\)/, 'virtual pointer transform must place the hotspot at the browserd x coordinate')
assert.match(style, /calc\(var\(--pointer-y\) - var\(--pointer-hotspot-y\)\)/, 'virtual pointer transform must place the hotspot at the browserd y coordinate')
assert.match(style, /transform-origin:\s*var\(--pointer-hotspot-x\) var\(--pointer-hotspot-y\)/, 'virtual pointer press scale must keep the cursor tip fixed')
assert.match(style, /paint-order:\s*stroke fill/, 'virtual pointer must keep a contrasting outline over arbitrary pages')
assert.match(style, /--pointer-x:\s*50vw/, 'virtual pointer must default to the horizontal center before events arrive')
assert.match(style, /--pointer-y:\s*50vh/, 'virtual pointer must default to the vertical center before events arrive')
assert.match(style, /opacity:\s*0\.96/, 'virtual pointer must be visible by default')
